halfcheetah-maml:
    env: HalfCheetahRandDirec-v2
    run: MAML
    stop:
        training_iteration: 1001
    config:

        # Sample Batch Size must equal Horizon!
        # Must Also be Complete Episdoes
        horizon: 100
        sample_batch_size: 100
        num_envs_per_worker: 20
        batch_mode: complete_episodes
        #======================================#
        inner_adaptation_steps: 1
        maml_optimizer_steps: 3
        gamma: 0.99
        lambda: 1.0
        lr: .0001
        vf_loss_coeff: 0.5
        clip_param: 0.3
        use_kl_loss: False
        kl_target: 0.01
        kl_coeff: 0.0005
        num_workers: 1
        num_gpus: 1
        inner_lr: 0.1
        model:
            concat_input_size: 10
            context_input_size: 1
            free_log_std: True
            # For Concat Experiments, set 'concat_context: True; 
            # and 'use_context: dynamic'
            concat_context: False
        # Context: dynamic, static, none
        use_context: none                     
