hopper-params-maml:
    env: HopperRandParams-v0
    run: MAML
    stop:
        training_iteration: 501
    local_dir: /data/mluo/hopper_random_parameters
    config:
        # Sample Batch Size must equal Horizon!
        # Must Also be Complete Episdoes
        horizon: 200
        sample_batch_size: 200
        num_envs_per_worker: 20
        batch_mode: complete_episodes

        inner_adaptation_steps: 1
        maml_optimizer_steps: 3
        gamma: 0.99
        lambda: 1.0
        lr: .001
        vf_loss_coeff: 0.5
        clip_param: 0.3
        num_workers: 40
        num_gpus: 1
        use_kl_loss: True
        kl_target: 0.01
        kl_coeff: 0.001
        model:
            free_log_std: True
            concat_context: False
            concat_input_size: 41
            context_input_size: 41
        inner_lr: 0.03
        use_context:
            grid_search: [none, none, none, none]                  
