fetch-maml:
    env: Reach-v1
    run: MAML
    stop:
        training_iteration: 1001
    local_dir: /data/mluo/fetch-env
    config:
        # Sample Batch Size must equal Horizon!
        # Must Also be Complete Episdoes
        horizon: 100
        sample_batch_size: 100
        num_envs_per_worker: 20
        batch_mode: complete_episodes

        gamma: 0.99
        lambda: 1.0
        lr: .0001
        vf_loss_coeff: 0.5
        clip_param: 0.3
        kl_coeff: 0.0005
        num_workers: 5
        num_gpus: 1
        model:
            free_log_std: True
            concat_context: False
        use_context:
            grid_search: [none, none, none, static, static, static, dynamic, dynamic, dynamic]                
