halfcheetah-maml:
    env: HalfCheetahRandDirec-v2
    run: MAML
    config:
        gamma: 0.99
        lambda: 1.0
        kl_coeff: 1.0
        num_sgd_iter: 32
        lr: .001
        vf_loss_coeff: 0.5
        clip_param: 0.3
        sample_batch_size: 100
        num_envs_per_worker: 20
        kl_coeff: 0.0005
        num_workers: 4
        num_gpus: 1
        grad_clip: 0.5
        num_envs_per_worker: 32
        horizon: 100
        batch_mode: complete_episodes
        observation_filter: MeanStdFilter                                         
