hopper-impala:
    env: Hopper-v2
    run: A2C
    local_dir: ./hopper-impala-results
    stop:
        time_total_s: 10800
    config:
        sample_batch_size: 200
        clip_rewards: True
        num_workers: 5
        num_envs_per_worker: 32
        num_gpus: 1
        lr: 0.0001
