hopper-impala:
    env: 
        grid_search: 
          - Ant-v2
          - Walker2d-v2
          - Reacher-v2
          - Ant-v2
          - Walker2d-v2
          - Reacher-v2
          - Ant-v2
          - Walker2d-v2
          - Reacher-v2
          - Ant-v2
          - Walker2d-v2
          - Reacher-v2
          - Ant-v2
          - Walker2d-v2
          - Reacher-v2
    run: IMPALA
    local_dir: ~/cont-impala-results
    stop:
        time_total_s: 10800
    config:
        gamma: 0.995
        num_sgd_iter:  20
        lr: .00001
        sample_batch_size: 4096
        train_batch_size: 32768
        num_envs_per_worker: 16
        vf_loss_coeff: 1.0
        entropy_coeff: 0.0
        minibatch_buffer_size: 5
        num_workers: 16
        num_gpus: 1
        batch_mode: truncate_episodes
        observation_filter: MeanStdFilter
