hopper-impala:
    env: Hopper-v2
    run: IMPALA
    local_dir: ./hopper-impala-results
    stop:
        time_total_s: 10800
    config:
        vtrace: True
        model: 
            vf_share_layers: False
        gamma: 0.995
        num_sgd_iter: 
            grid_serach: [20, 20, 20]
        lr: .0001
        broadcast_interval: 1
        max_sample_requests_in_flight_per_worker: 1
        sample_batch_size: 2048
        train_batch_size: 32768
        num_envs_per_worker: 32
        vf_loss_coeff: 1.0
        entropy_coeff: 0.0
        minibatch_buffer_size: 5
        num_workers: 10
        num_gpus: 1
        grad_clip: 0.5
        batch_mode: truncate_episodes
        observation_filter: MeanStdFilter
