hopper-ppo:
    env: Hopper-v2
    run: APPO
    local_dir: /data/mluo/hopper-appo-results
    stop:
        time_total_s: 10800
    config:
        vtrace: true
        gamma: 0.995
        num_sgd_iter: 32
        minibatch_buffer_size: 5
        lr: .0001
        train_batch_size: 8192
        sample_batch_size: 1024
        num_workers: 16
        num_gpus: 1
        broadcast_interval: 1
        max_sample_requests_in_flight_per_worker: 1
        num_data_loader_buffers: 1
        num_envs_per_worker: 32 
        batch_mode: truncate_episodes   
        clip_param: 0.3
        vf_loss_coeff: 1.0
        entropy_coeff: 0.0
        grad_clip: 0.5 
        use_kl_loss: True
        kl_coeff: 1.0
        kl_target: 0.02             
        observation_filter: MeanStdFilter

