humanoid-ppo-gae:
    env: Humanoid-v2
    run: PPO
    local_dir: /data/mluo/humanoid-ppo-results
    config:
        gamma: 0.995
        lambda: 0.95
        clip_param: 0.2
        kl_coeff: 1.0
        num_sgd_iter: 20
        lr: .0001
        sgd_minibatch_size: 32768
        horizon: 5000
        train_batch_size: 320000
        model:
            free_log_std: true
        num_workers: 16
        num_gpus: 1
        batch_mode: truncate_episodes
        observation_filter: MeanStdFilter
