humanoid-maml:
    env: HumanoidRand2D-v2
    run: MAML
    stop:
        training_iteration: 501
    local_dir: /data/mluo/humanoid-concat-context
    config:
        # Sample Batch Size must equal Horizon!
        # Must Also be Complete Episdoes
        horizon: 200
        sample_batch_size: 200
        num_envs_per_worker: 20
        batch_mode: complete_episodes

        inner_adaptation_steps: 1
        maml_optimizer_steps: 5
        gamma: 0.99
        lambda: 1.0
        lr: .0001
        vf_loss_coeff: 0.5
        clip_param: 0.3
        kl_coeff: 0.0005
        num_workers: 40
        num_gpus: 1
        model:
            fcnet_hiddens: [128, 128]
            concat_input_size: 10
            context_input_size: 2
            hyper_hiddens: [64, 64, 64]
            free_log_std: True
            concat_context: 
                grid_search: [True, True, True]
        inner_lr: 0.1
        use_context: dynamic           
