humanoid-ppo-gae:
    env: Humanoid-v2
    run: APPO
    local_dir: /data/mluo/humanoid-appo-testing
    stop:
        time_total_s: 10800
    config:
        vtrace: true
        use_kl_loss: True
        kl_coeff: 1.0
        kl_target: 0.02
        vf_loss_coeff: 1.0
        entropy_coeff: 0.0
        gamma: 0.995
        lambda: 0.95
        clip_param: 0.2
        kl_coeff: 1.0
        num_sgd_iter: 25
        lr: .0001
        sgd_minibatch_size: 32768
        horizon: 5000
        train_batch_size: 320000
        model:
            free_log_std: true
        num_workers: 16
        num_gpus: 1
        broadcast_interval: 1
        max_sample_requests_in_flight_per_worker: 1
        num_data_loader_buffers: 1
        batch_mode: truncate_episodes
        observation_filter: MeanStdFilter
