humanoid-impala:
    env: Humanoid-v2
    run: IMPALA
    local_dir: /data/mluo/humanoid-impala-results
    stop:
        time_total_s: 10800   
    config:
        vtrace: False
        model: 
            vf_share_layers: False
        gamma: 0.995
        sample_batch_size: 256
        train_batch_size: 4096
        num_workers: 16
        num_gpus: 1
        broadcast_interval: 1
        max_sample_requests_in_flight_per_worker: 1
        num_data_loader_buffers: 1
        num_envs_per_worker: 16
        minibatch_buffer_size: 1
        num_sgd_iter: 1
        lr: .00001
        vf_loss_coeff: 0.5
        entropy_coeff: 0.0
        grad_clip: 0.5
        batch_mode: truncate_episodes
        observation_filter: MeanStdFilter
