metaworld-maml:
    env: reach-v1
    run: MAML
    stop:
        training_iteration: 1001
    local_dir: /data/mluo/multiworld-testing
    config:
        # Sample Batch Size must equal Horizon!
        # Must Also be Complete Episdoes
        horizon: 100
        sample_batch_size: 100
        num_envs_per_worker: 10
        batch_mode: complete_episodes

        inner_adaptation_steps:
            grid_search: [2,4]
        maml_optimizer_steps: 5
        gamma: 0.99
        lambda: 1.0
        lr: .0001
        vf_loss_coeff: 0.5
        clip_param: 0.3
        kl_coeff: 0.0005
        num_workers: 20
        num_gpus: 1
        model:
            concat_input_size: 10
            context_input_size: 2
            free_log_std: True
            concat_context: True
        inner_lr: 0.05
        use_context:
            grid_search: [none, none]             
