reach-concat-false-new-hyper-design:
    env: reach-v1
    run: MAML
    stop:
        training_iteration: 2001
    local_dir: /data/mluo/metaworld-static-goals
    config:
        # Sample Batch Size must equal Horizon!
        # Must Also be Complete Episdoes
        horizon: 150
        sample_batch_size: 150
        num_envs_per_worker: 5
        batch_mode: complete_episodes
        vf_loss_coeff: 0.5
        inner_adaptation_steps: 4
        maml_optimizer_steps: 5
        gamma: 0.99
        lambda: 1.0
        lr: .0003
        clip_param: 1.0
        kl_coeff: 0.000
        kl_target: 0.01
        num_workers: 20
        num_gpus: 1
        model:
            hyper_hiddens: [64, 64]
            concat_input_size: 15
            context_input_size: 3
            free_log_std: True
            concat_context: False
        inner_lr: 0.05
        use_context: dynamic

