sawyer-simple-maml:
    env: SawyerSimple-v0
    run: MAML
    stop:
        training_iteration: 501
    local_dir: /data/mluo/sawyer-simple-results
    config:
        # Sample Batch Size must equal Horizon!
        # Must Also be Complete Episdoes
        horizon: 150
        sample_batch_size: 150
        num_envs_per_worker: 80
        batch_mode: complete_episodes

        inner_adaptation_steps: 1
        maml_optimizer_steps: 5
        gamma: 0.99
        lambda: 1.0
        lr: .0005
        vf_loss_coeff: 0.5
        clip_param: 0.3
        kl_coeff: 0.001
        kl_target: 0.01
        use_kl_loss: True
        num_workers: 20
        num_gpus: 1
        model:
            fcnet_hiddens: [128, 128]
            hyper_hiddens: [64, 128]
            concat_input_size: 18
            context_input_size: 6
            free_log_std: True
            concat_context: False
        inner_lr: 0.05
        use_context: static       
