walker-params-maml:
    env: Walker2DRandParams-v0
    run: MAML
    stop:
        training_iteration: 1001
    local_dir: /data/mluo/walker_rand_params
    config:
        # Sample Batch Size must equal Horizon!
        # Must Also be Complete Episdoes
        horizon: 200
        sample_batch_size: 200
        num_envs_per_worker: 20
        batch_mode: complete_episodes

        inner_adaptation_steps: 1
        maml_optimizer_steps: 5
        gamma: 0.99
        lambda: 1.0
        lr: .0001
        vf_loss_coeff: 0.5
        clip_param: 0.3
        kl_coeff: 0.0005
        num_workers: 40
        num_gpus: 1
        model:
            free_log_std: True
            concat_context: False
            concat_input_size: 65
        use_context: 
            grid_search: [none, static, dynamic, none, static, dynamic, none, static, dynamic]                  
